const products = [
  {
    id: 1,
    img: "./images/products_img/img_1.jpg",
    name: "Роза",
    views: 20,
    bestseller: true,
    price: 1000,
    sale: 0,
    categoryId: 1,
  },
  {
    id: 2,
    img: "./images/products_img/img_2.jpg",
    name: "Тюльпан",
    views: 25,
    bestseller: false,
    price: 2000,
    sale: 15,
    categoryId: 1,
  },
  {
    id: 3,
    img: "./images/products_img/img_3.jpg",
    name: "Лаванда",
    views: 30,
    bestseller: true,
    price: 4500,
    sale: 0,
    categoryId: 3,
  },
  {
    id: 4,
    img: "./images/products_img/img_4.jpg",
    name: "Ландыш",
    views: 2,
    bestseller: false,
    price: 5000,
    sale: 20,
    categoryId: 2,
  },
  {
    id: 5,
    img: "./images/products_img/img_5.jpg",
    name: "Пион",
    views: 28,
    bestseller: true,
    price: 2000,
    sale: 50,
    categoryId: 2,
  },
  {
    id: 6,
    img: "./images/products_img/img_6.jpg",
    name: "Одуванчик",
    views: 200,
    bestseller: false,
    price: 1800,
    sale: 0,
    categoryId: 3,
  },
  {
    id: 7,
    img: "./images/products_img/img_7.jpg",
    name: "Ромашка",
    views: 120,
    bestseller: true,
    price: 3000,
    sale: 30,
    categoryId: 1,
  },
  {
    id: 8,
    img: "./images/products_img/img_8.jpg",
    name: "Кактус",
    views: 120,
    bestseller: true,
    price: 1300,
    sale: 70,
    categoryId: 5,
  },
];
